config/routes.rb
AlbumApp::Application.routes.draw do
  devise_for :users

  resources :users

  resources :albums
  root :to => "albums#wall"
  match "wall" => "albums#wall"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :images_attributes
  has_many :images, :as => :picture, :class_name => "Image"
  accepts_nested_attributes_for :images,:allow_destroy => true
  belongs_to :user

  def images_other_than_cover
    Image.where("picture_id = ? and picture_type = ? and cover_pic is NULL",self.id, "Album")
  end

  def cover_pic
    Image.where("picture_id = ? and picture_type = ? and cover_pic IS NOT NULL",self.id, "Album")
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :picture, :cover_pic
  belongs_to :picture, :polymorphic => true
  has_attached_file :picture
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  def user
    User.find(self.picture_id) if self.picture_type.eql?("User")
  end

  def album
    Album.find(self.picture_id) if self.picture_type.eql?("Album")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :about_me, :birthdate, :full_name, :profile_picture_attributes
  has_one :profile_picture,:class_name => "Image", :as => :picture
  accepts_nested_attributes_for :profile_picture
  has_many :albums
  has_many :images, :through => :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
   before_filter :authenticate_user!, :except => [:wall]
  # GET /albums
  # GET /albums.json
  def index
    @users = User.where(:id => current_user.id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.build(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  def wall
    @users = User.all
    respond_to do |format|
      format.html { render :template => "albums/index" }
      format.json { render json: @albums }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource_or_scope)
    "/users/#{current_user.id}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_filter :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        #@user.profile_picture.picture_id = current_user.id if @user.profile_picture
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= nested_form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.fields_for :images do |image_form| %>
    <%= image_form.label :set_cover_pic %>
    <%= image_form.radio_button :cover_pic, "0", :onclick => "$(this).val('1')" %>
    <%= image_form.file_field :picture %>
    <%= image_form.link_to_remove "Remove this picture" %>
  <% end %>
  
  <p><%= f.link_to_add "Add a picture", :images %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<% @users.each do |user| %>
    <% user.albums.each do |album| %>
      <div class="img">
        <a href="<%= album_path(album) %>"><img src="<%= album.cover_pic.first.picture.url rescue nil%>" alt="<%= album.name %>" width="110" height="90">
        <div class="desc"><%= album.user.full_name %></div>
        <% if user_signed_in?  %>
          <%= link_to "Edit Album", edit_album_path(album) %>
      <% end %></a>
      </div>
    <% end %>
<% end %>

<div class = "desc">
<% if user_signed_in? %>
  <%= link_to "Create Album", new_album_path %>
<% end %>
</div>

<style>
div.img
  {
  margin:5px;
  padding: 5px;
  border:1px solid #0000ff;
  height:auto;
  width:auto;
  float:left;
  text-align:center;
  }
div.img img
  {
  display:inline;
  margin:5px;
  border:1px solid #ffffff;
  }
div.img a:hover img
  {
  border:1px solid #0000ff;
  }
div.desc
  {
  text-align:center;
  font-weight:normal;
  width:120px;
  margin:5px;
  }
</style>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Name:</b>
	<%= @album.name %>
</p>
<p>
	<b>Cover pic:</b>
	<% if !@album.cover_pic.blank? %>
	<%= image_tag(@album.cover_pic.first.picture.url,:width => 100, :height => 100) %>
	<%end%>
</p>
Album images:
<% @album.images_other_than_cover.each do |image| %>
<p>
	<%= image_tag(image.picture.url,:width => 100, :height => 100) rescue nil %>
</p>
<% end %>
<%= link_to 'Edit', edit_album_path(@album) %> |<%= link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_header.html.erb
<div>
<% if user_signed_in? %>
  <%= link_to "Profile", "/users/#{current_user.id}" %>
  <%= link_to 'My albums', albums_path %>
  <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Log In", "users/sign_in" %>
<% end %>
</div>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlbumApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= nested_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :about_me %><br />
    <%= f.text_area :about_me %>
  </div>

  <div class="field">
  <%= f.fields_for :profile_picture do |image_form| %>
    Profile picture:
    <%= image_form.file_field :picture %>
     <% if @user.profile_picture %>
      <p><%= image_form.link_to_remove "Remove this picture" %></p>
    <% end %>
  <% end %>
  
  </div>
  <% unless @user.profile_picture %>
    <p><%= f.link_to_add "Add a picture", :profile_picture, :onclick => "$(this).hide();" %></p>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Birthdate</th>
    <th>About me</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.full_name %></td>
    <td><%= user.birthdate %></td>
    <td><%= user.about_me %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <% if @user.profile_picture.try(:picture) %>
    <%= image_tag(@user.profile_picture.picture.url) %>
  <% else %>
    No profile picture.
  <% end %>
</p>
<p>
  <b>Full name:</b>
  <%= @user.full_name %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @user.birthdate %>
</p>

<p>
  <b>About me:</b>
  <%= @user.about_me %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %>